[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''love.audio.stop()'''
position = "after"
payload = '''
if pipe_crash_sound and pipe_crash_sound.key then
    pcall(play_sound, pipe_crash_sound.key)
end
'''
match_indent = true
